### PR TITLE
Title element is reused when necessary

### LINKED ISSUE #325: Discrepancy between the spec and the canonical manifest on title
The current text says, for [title](https://w3c.github.io/wpub/#wptitle):

> If not included in the manifest, user agents _MAY_ use the value of the title element [html] of the Web Publication’s primary entry page (if present).

Whereas the first step in the [canonical manifest algorithm](https://w3c.github.io/wpub/#canonical-manifest) re-uses the title element of the primary entry page in all cases if the `name` value is not in the manifest.

### PR DESCRIPTION
**Pull request by iherman**
Adopted wording in https://github.com/w3c/wpub/pull/331#issuecomment-436199708. That comment is a proposal to close a long-standing issue.

Fix #325 

Replaces #331 (and closing that one)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/pull/363.html" title="Last updated on Nov 12, 2018, 3:56 PM GMT (adfa088)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/363/8655342...adfa088.html" title="Last updated on Nov 12, 2018, 3:56 PM GMT (adfa088)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
To make the possible discussion here simpler and not forcing to go back to other issues, the changes are:

- The `name` entry for the document (a.k.a. title) is a required element
- If the `name` is not specified in the (authored) manifest, the content of the `title` element in the primary entry page is used instead. This is done via the step in the canonical manifest.
- If the title element does not exist either, the UA must perform a heuristics to add an entry, although the heuristics itself is not specified (examples in the text)

**Comment by llemeurfr** [comment]
Also, the term "as a non-zero title element" is a mystery for me. I believe it means non empty, but ...

**Comment by iherman** [comment]
> Also, the term "as a non-zero title element" is a mystery for me. I believe it means non empty, but ...

It is also a mystery for me:-) Changed it to non empty

**Comment by iherman** [comment]
@llemeurfr 

> allow an empty title in the manifest

I am fine with this. (I am not sure how this statement got into the draft in the first place.)

However, one step further then: the heuristics the UA can use if neither the `name` nor the `title` is present may also include explicitly the possibility to use an empty `name`. Although that section is not really normative, I guess it is better to make this explicit. WDYT?

**Comment by iherman** [comment]
@llemeurfr you convinced me:-) I removed the reference to an emtpy title.

**Comment by iherman** [comment]
@llemeurfr @TzviyaSiegman @wareid @mattgarrish is it o.k. to merge this?

**Pull request merged**
