### PR TITLE
Run ReSpec sync instead

### PR DESCRIPTION
**Pull request by marcoscaceres**
Should avoid race conditions.... otherwise try:

```HTML
<script src="https://www.w3.org/Tools/respec/respec-w3c-common" class="remove" defer></script>
```

### CODE REVIEW

**Comment by iherman** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by iherman** [comment]
Actually, what did the trick was the usage of `defer`.

**Comment by marcoscaceres** [comment]
Great to hear that one of the solutions worked. Frustrated that I wasn't able to reproduce the bug 😿

**Comment by iherman** [comment]
> Great to hear that one of the solutions worked. Frustrated that I wasn't able to reproduce the bug 😿
> 
> 

Wouldn't life be boring otherwise?

**Comment by marcoscaceres** [comment]
Indeed 🍾

**Pull request merged**
