### PR TITLE
Lifecycle update

### PR DESCRIPTION
**Pull request by iherman**
Made a fairly complete rewrite of the Lifecycle section (section 6), trying to get it aligned with the rest.

I have also added a number of "checks" as part of the manifest processing steps. I am not 100% that all of them are necessary. E.g., a bad date is something that browsers already handle, we may not have to add a special step for that; the same for badly formed URL-s. (That is also why I have not added a check for badly formed language or base direction tags.) Comments particularly on this would be welcome...

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/pull/318.html" title="Last updated on Aug 31, 2018, 10:44 AM GMT (d29602b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/318/0e4c801...d29602b.html" title="Last updated on Aug 31, 2018, 10:44 AM GMT (d29602b)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
Actually... I wonder whether the title shouldn't be: "Web Publication Manifest Lifecycle"

**Comment by iherman** [comment]
@HadrienGardeur @mattgarrish is it o.k. to merge this PR? It brings the full manifest definition, lifecycle, diagrams, etc, in sync. I think having them in sync would be better before further possible changes (eg, as a result of the TOC discussions or, later, the audiobook additions)

**Comment by iherman** [comment]
@TzviyaSiegman see previous question (forgot to cc you, sorry)

**Comment by TzviyaSiegman** [comment]
looks good. Thank you. I think we can merge.

**Pull request merged**
