### PR TITLE
First attempt at crafting a JSON-LD context

### PR DESCRIPTION
**Pull request by HadrienGardeur**
Based on our discussion in #212 here’s a first draft of the context document.

### CODE REVIEW

**Comment by iherman** [comment]
My reading of, eg, the example at https://bib.44.20180402t222137.schemaorgae.appspot.com/colorist but also the fact that the original schema.org json context has a "@vocab" set to "schema.org" is that even terms originating from the "bib" extension of schema.org are represented by URLs in the "schema.org" space. In other words, the mapping of, say, "colorist" is to be "http://schema.org/colorist". 

If that is correct then:

- our context file should not include anything on "colorist"
- we should require (as it is in the draft) to include the schema.org context file into the manifest, which would provide the right "@vocab"

Am I missing something?

**Comment by iherman** [comment]
We will have some enjoyable bikeshedding on setting the terms:-)

**Comment by llemeurfr** [comment]
Can we really remove refs to bib.schema.org?
... http://schema.org/colorist leads to "The term 'colorist' is not in the schema.org core vocabulary, but is defined in an extension: bib: colorist"
... and http://bib.schema.org/colorist leads to the proper page.

**Comment by llemeurfr** [comment]
ok, I see that now, and in the bib page the note: "extension terms can be used in schema.org markup in the normal manner; it is not necessary for markup publishers to indicate which extension a term is currently in. Terms may move between extensions over time (e.g. from pending to the core) without the need for the corresponding markup to change."

**Comment by iherman** [comment]
> 
> Can we really remove refs to bib.schema.org <http://bib.schema.org/>?
> ... http://schema.org/colorist <http://schema.org/colorist> leads to "The term 'colorist' is not in the schema.org <http://schema.org/> core vocabulary, but is defined in an extension: bib: colorist"
> ... and http://bib.schema.org/colorist <http://bib.schema.org/colorist> leads to the proper page.
> 
> 

That is correct but that is not what counts: if you look at the JSON-LD example on that page, they only use the schema.org <http://schema.org/> context file, ie, the term is mapped onto "http://schema.org/colorist <http://schema.org/colorist>". it is a bit weird, I agree, but not our decision…

(B.t.w., there is now a redirection of https://www.w3.or/ns/wpub.jsonld <https://www.w3.or/ns/wpub.jsonld> to the github version. It is temporary, ie, at some point it should be a hard content.)

**Comment by HadrienGardeur** [comment]
@iherman thanks for the redirection. 

Tried a few more examples with that and it looks like we need to add an `@id` for `resources` as well, otherwise it gets rejected by the JSON-LD playground.

**Pull request merged**
