### PR TITLE
Allow retention of html tagging in toc extraction

### PR DESCRIPTION
**Pull request by mattgarrish**
This PR addresses #414 as follows:

- it provides the option to retain either the child content or generate a string (for the toc heading and entries)
- it only suggests using the accessible name computation algorithm to provide greater flexibility in how strings are generated

One downside of the flexibility is that it's not always clear when the child content will result in an empty string -- trimming whitespace isn't enough when retaining tagging. Trying to write out steps for that just gets us back to generating strings, so I've only stated in a parenthetical some things that would be involved, like removing whitespace and presentational tagging).

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/pull/452.html" title="Last updated on May 27, 2019, 12:27 PM UTC (1204f60)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/452/a5149c7...1204f60.html" title="Last updated on May 27, 2019, 12:27 PM UTC (1204f60)">Diff</a>

### CODE REVIEW

**Comment by mattgarrish** [comment]
I added a description of why we list two options to the explanations for the relevant steps, but its a user agent processing section so every step is the user agent doing something. What clarification would you put at the top?

If you can get a real example of some useful markup to retain, that would be immeasurably better than anything I could fake.

**Comment by iherman** [comment]
> 
> I added a description of why we list two options to the explanations for the relevant steps, but its a user agent processing section so every step is the user agent doing something. What clarification would you put at the top?
> 
> 

Ok, what you added may be indeed enough.

> If you can get a real example of some useful markup to retain, that would be immeasurably better than anything I could fake.
> 

I will

**Comment by mattgarrish** [comment]
> Ok, what you added may be indeed enough.

If it helps, I've added this sentence to the second paragraph:

> In some steps, user agents are provided a choice in how to process the content to provide flexibility for different presentation models.

**Comment by iherman** [comment]
@mattgarrish I would propose to merge this. Daihei or Naomi may give us an extra example using Ruby that we can add later, but we should avoid potential merge issues...

**Pull request merged**
