### PR TITLE
Added a paragraph on the landing page in the lifecycle section

### PR DESCRIPTION
**Pull request by iherman**
This is an attempt to include in the document the emerging consensus on issue #94.

***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/wpub/landing-page.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/wpub/256a2e9...072e663.html)

### CODE REVIEW

**Comment by mattgarrish** [comment]
I only wonder if these requirements belong under the Address section itself (better understanding by proximity).

Substantively, though, I have no problem with it. We can always tweak locations later.

**Comment by lrosenthol** [comment]
Why does the landing page have to be HTML?  Why can't it be SVG or an image?

**Comment by dauwhe** [comment]
> @iherman Why does the landing page have to be HTML? Why can't it be SVG or an image?

An image can't contain a link to the manifest.

**Comment by lrosenthol** [comment]
@dauwhe it can in the link header, which is one of the ways to link back (as described elsewhere in the doc)

**Comment by mattgarrish** [comment]
HTML may be restrictive, but the point made by Florian that images and audio and video are not the "web" was a good one and still resonates with me. Even if there are ways of rendering such media for WPUB-aware user agents, they can't be made usable for vanilla implementations. A link header is effectively useless. Asking for one HTML file for those media types seems like a fair trade-off for usability.

I personally feel like we're biting off more than we can chew in taking such a liberal view that anything that can be hosted on a web server is a potential web publication or candidate for inclusion in the default reading order, but I don't want to cause a 100 comment argument here... :)

**Comment by lrosenthol** [comment]
I didn't hear Florian say that, but I disagree completely.  The OWP is well defined (<https://www.w3.org/wiki/Open_Web_Platform>) and clearly includes more than HTML.

**Comment by mattgarrish** [comment]
They're are technologies used on the Web, yes, but they are not how users navigate the Web, which is the point here. HTML is the backbone of the web that brings those resources together.

I can't move from jpeg to jpeg, for example, or audio clip to audio clip. We're attempting to solve that here, but in a way that isn't compatible with the Web as it exists.

**Comment by iherman** [comment]
Coming back to the original comment of @lrosenthol: yes, indeed, we do refer to the possibility of referring to the manifest via the HTTP return header. However:

* It turns out to be very complicated for lambda users (and many system managers) to set up such return headers correctly
* Although I am not familiar with all the details, I believe that browsers would not make it easy for extensions, javascript programs, whatever, to have access to the return header of an HTML file (it is not part of the DOM) let alone the return header for an image

Let me add: alas! The HTTP return headers is an underutilized part of the architecture (I think), but we must be pragmatic. The proposal referring to the `<link>` element tries to be pragmatic and avoid shooting in our own foot...

**Comment by lrosenthol** [comment]
Well, we at least agree on SVG - so MUST be HTML won't work.

**Comment by iherman** [comment]
@lrosenthol the "real" content may be SVG (e.g., a series of Manga images). That is not contradictory to a requirement that the landing page is in HTML.

SVG does not have a `<link>` element that we could use, for example.

**Comment by BigBlueHat** [comment]
@iherman this PR mentions not having a definition for the structure of the Table of Contents, but farther down the document we do have that definition: https://w3c.github.io/wpub/#wp-table-of-contents

Other than that, I'm +1.

**Comment by iherman** [comment]
Oops @BigBlueHat, good catch! I have put a reference to that section, removed the editor's note and added an editor's note in the section you referred to that it should be brought to sync with this new addition. I am too tired to do anything else right now (and I travel back home tomorrow).

I may try to propose a sync in [that section](https://w3c.github.io/wpub/#wp-table-of-contents) on Monday, unless @mattgarrish beats me into it:-)

**Comment by mattgarrish** [comment]
What I'm going to do here is merge this prose but suggest we leave open #94 for further discussion (i.e., in the vein of just because we've added prose doesn't mean it is set in stone).

In addition to looking at toc overlap, I'd like to do some further restructuring, such as setting up a "content" section for the landing page description and also the "linking to a manifest" section. I'd also like to do some more general review before fpwd, and leaving this open gets in the way.

**Comment by HadrienGardeur** [comment]
In reply to @iherman 

> SVG does not have a `<link>` element that we could use, for example.

No need for such an element when you can rely on the `Link` header in HTTP.

**Comment by iherman** [comment]
@HadrienGardeur this is of course related to the #94. You are right that, in general, a Link header would suffice, but this comment came about on whether a pure SVG file could play the role of a landing page or not.

**Pull request merged**
