### PR TITLE
Language and dir rewrite

### LINKED ISSUE #220: Setting the (text) direction
This is a completely open issue at this moment, both for JSON-LD and Schema.org... The only (incomplete) approach would be to rely on, and base everything, on the UTF-encoding of the text...

### PR DESCRIPTION
**Pull request by iherman**
This is the version is agreed on the Telco 2018-08-23.

Fix #220

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/pull/275.html" title="Last updated on Jul 25, 2018, 11:08 AM GMT (b122f0d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/275/007d7fc...b122f0d.html" title="Last updated on Jul 25, 2018, 11:08 AM GMT (b122f0d)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
@TzviyaSiegman could you also have a look at appendix C, please, to see if it is o.k.?

**Comment by llemeurfr** [comment]
In 4.4.5 I would rather define the language as the "natural language of the publication", and in the infoset requirement add that it also specifies the natural language of the textual values; not the reverse. 

I would also explain in 4.4.5 that the base direction is the "base direction of the publication", and move the first note of 4.4.5.1 there (it's functional).

In 4.4.5.1 I would remove "(i.e., if the base direction is set) ". 

In the definition of inLanguage and inDirection I would put the emphasis on its use at the level of the publication ("Default language for the Web Publication as well as for textual values").

In the note 4.4.5.2.1 the is a typo:  it is RECOMMENDED to **use set** these properties 
and IMO an error: the containing **link** element in case of **embedding**

Note that I'm still not convinced at all about the practical use of the base direction (for UI needs + as indication for text directionality). And as I said yesterday I don't support the difference of processing between embedded and detached manifests. But I'll move these rants elsewhere.

**Comment by iherman** [comment]
@llemeurfr thanks. I have made those changes; can you check and, if you are o.k. with merging, give your thumbs up?

(I have made the issue on inheritance explicit in the text)

**Comment by llemeurfr** [comment]
In the note in 4.4.5.1, I would argue that there should be no notion of override in "it is possible to set, e.g., the language for that resource individually, which will override the global setting for the publication as a whole." and make it required or recommended. -> ""it is recommended to set the language and base direction for each resource individually."

Apart from that, thumbs up for me.

**Comment by mattgarrish** [comment]
I think we could just make the note about placement into a parenthetical. There are also some normative keywords in lower case. Do you want me to make some small adjustments to fix these?

**Comment by iherman** [comment]
@mattgarrish please do; I have some other stuff to worry about.

@llemeurfr is fine with the PR and unless @TzviyaSiegman has objections, I guess you should merge this (and the other two PR-s actually)

**Comment by TzviyaSiegman** [comment]
@iherman in App C, the third example "displayed as" - Hebrew is correct, but the english is displaying as RTL.

**Comment by iherman** [comment]
@TzviyaSiegman do you think it is possible to merge the whole thing and you can then edit the example? It is less error prone than me doing it...

**Comment by TzviyaSiegman** [comment]
@iherman I can try!

**Comment by r12a** [comment]
Do you want me to look at the Hebrew example ?

**Comment by iherman** [comment]
@r12a yes please, if you can also have a look!

**Comment by iherman** [comment]
@TzviyaSiegman it seems that @mattgarrish wants to do a small editorial change; I would leave to him to merge this PR

**Comment by r12a** [comment]
is it the lines from 3100 onwards?

**Comment by iherman** [comment]
@r12a Appendix C

**Comment by iherman** [comment]
@r12a https://pr-preview.s3.amazonaws.com/w3c/wpub/pull/275.html#bidi-examples

**Comment by r12a** [comment]
@iherman what should the column "Displayed as" show? Is it what you would expect to see if some link in the chain correctly interpreted the presence of the RLM/LRM as meaning "put something around this string in the target location to make it have the correct base direction"?

**Comment by iherman** [comment]
@r12a Well... I originally expected the "value" to show the string the way it is stored in a program. But then I realized that even a usual screen editor (I use SublimeText) probably shows the hebrew characters in the display mode when in HTML and not as it is stored inside.... I am not sure how to achieve that. The right hand column is the way one would expect to see it.

**Comment by r12a** [comment]
Bidi code sent by email, btw.

**Comment by mattgarrish** [comment]
I've done some minor cleanup on this: removing normative keywords where we aren't really say anything normative, and also from notes, which by definition are informative.

One thing I found concerning (and I see this elsewhere in the spec), is that there are times where we indicate to see another specification, without being specific what we're referring people to (e.g., "(see [html])"). It would be good to root these out and be more specific about what section we're referring to so that readers don't have to hunt down the information for themselves.

**Comment by iherman** [comment]
@mattgarrish, on https://github.com/w3c/wpub/pull/275#issuecomment-407494431: actually, the links to the handling of `lang` and `dir` were linked from the document itself, but it was not really clear. I did make some minor editorial change to make it clearer. That being said, a review of the document as whole for this would be indeed useful.

**Comment by mattgarrish** [comment]
Thanks, that was my issue: does the reference simply refer to previous links or does it mean there is something else the user has to look up. Clearer now.

**Pull request merged**
