### PR TITLE
Added a new information item for progression direction.

### PR DESCRIPTION
**Pull request by iherman**
Fixes issue #126

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/pull/142.html" title="Last updated on Mar 1, 2018, 9:32 AM GMT (679f6d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/142/5319fb5...679f6d1.html" title="Last updated on Mar 1, 2018, 9:32 AM GMT (679f6d1)">Diff</a>

### CODE REVIEW

**Comment by dauwhe** [comment]
As @BigBlueHat mentioned on the call, there are only two values for page progression direction. Within HTML resources, CSS does allow for overflow in both x and y axes. If a publication resource scrolls "down," it might be a better reading experience for the next resource to appear below. Do we need a "top to bottom" direction?

**Comment by iherman** [comment]
@dauwhe, better discuss this on #126, because this PR is really only a write-up of the discussion and conclusion that happened there...

(I will copy this issue over there, just to save you time...)

**Comment by gardenia-corp** [comment]
How about default direction to "Reading System can choose default direction" which is same as idpf defined (http://www.idpf.org/epub/30/spec/epub30-publications.html#sec-spine-elem)? It mightbe convenient when we need to convert from idpf to web infoset.

**Comment by rakutenjeff** [comment]
How about default direction to "Reading System can choose default direction" which is same as idpf defined (http://www.idpf.org/epub/30/spec/epub30-publications.html#sec-spine-elem)? It mightbe convenient when we need to convert from idpf to web infoset.

**Comment by iherman** [comment]
@rakutenjeff : I am fine with what you propose and happy to do it if we have a consensus on the PR overall...

**Comment by mattgarrish** [comment]
My take is we merge this PR and continue to work out any additional details in separate issues, so that's what I'll do. :)

Nothing is written in stone yet.

**Comment by rakutenjeff** [comment]
Thanks @iherman Do you mind if I record it as a new issue since this is merged? Beside the default progression I was hoping wpub could have consistency with epub. And further more, my image of relationship between wpub and epub is wpub define what should be in manifest (and maybe define json serialization as well), and epub address those manifest items in packaged wp (epub) domain. So the manifest should be compatible. The benefit is current publisher who already has millions of epubs would be easy to step into WP stage in the future.

**Comment by iherman** [comment]
@rakutenjeff of course, by all means! Please do.

**Pull request merged**
