### PR TITLE
Removed "Processing the default reading order"

### PR DESCRIPTION
**Pull request by HadrienGardeur**
Based on our F2F discussions, I’ve removed the section dedicated to processing the default reading order.

This will require an additional commit/PR from @iherman to also update the diagrams (I don’t have the source files for them).

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/pull/206.html" title="Last updated on Jun 4, 2018, 5:00 PM GMT (4232358)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wpub/206/e6f2c3f...4232358.html" title="Last updated on Jun 4, 2018, 5:00 PM GMT (4232358)">Diff</a>

### CODE REVIEW

**Comment by HadrienGardeur** [comment]
We would also need to update https://w3c.github.io/wpub/#wp-default-reading-order but I thought that this belonged in a separate PR. Any thoughts from @mattgarrish or @iherman?

**Comment by iherman** [comment]
I will modify the diagrams probably tomorrow. Let us not merge this PR separately; I will make a commit with the changes.

B.t.w., for the future, the sources are in https://drive.google.com/drive/folders/1ZemrN4pAzHYLHcjZnI8i89Y6zTQirAjq

**Comment by iherman** [comment]
@HadrienGardeur @mattgarrish I have removed the unnecessary images and modified one.

@mattgarrish still have to find out why the images are so small (they are in SVG, they shouldn't be...)

**Comment by iherman** [comment]
I merge this, and would deal with other changes (eg, https://w3c.github.io/wpub/#wp-default-reading-order) separately when @mattgarrish is back.

**Pull request merged**
