### PR TITLE
clarify in scope the intent to facilitate different UA models

### PR DESCRIPTION
**Pull request by mattgarrish**
Not asked for, but this seems to be a question we realize we're all struggling to resolve in our minds as we consider how initiation and consumption of web publications occurs.

I think it would be good to say something about staying open to different models, but won't shed any tears if it passes a short unloved life and disappears.

***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/wpub/target-ua.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/wpub/fe59e27...38bdbad.html)

### CODE REVIEW

**Comment by dauwhe** [comment]
I think this should have a short life as a pull request, and a long life as an actual part of the document. I vote merge!

**Comment by iherman** [comment]
Merge it before the different PR begin to creating chaos:-)

**Comment by lrosenthol** [comment]
I agree - merge it!

**Comment by mattgarrish** [comment]
Will do. Just wanted to write them all up before memories faded.

**Pull request merged**
