### PR TITLE
add link to privacy policy as an infoset item

### PR DESCRIPTION
**Pull request by mattgarrish**
Based on the discussions at TPAC, here's a first attempt at adding a link to a privacy policy as a recommended property in the infoset.

Comments welcome, as always.

***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/wpub/infoset-privacy.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/wpub/fe59e27...05a8a80.html)

### CODE REVIEW

**Comment by iherman** [comment]
Merge it! +1

**Comment by lrosenthol** [comment]
I requested one minor editorial change on the PR and then I am fine with merging

**Comment by mattgarrish** [comment]
@lrosenthal I was trying to reflect the importance of privacy that was raised in the discussion without using rfc keywords. Would "important part" work as an alternative for you?

**Comment by mattgarrish** [comment]
Sorry phone auto corrected your id and i can't mod  @lrosenthol

**Comment by lrosenthol** [comment]
important part works for me - thanks @mattgarrish

**Pull request merged**
